ARG VARIANT="current-alpine3.15"
FROM node:${VARIANT}
RUN apk --no-cache add git

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
